# Use Python slim
FROM python:3.11-slim

WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y libglib2.0-0 libgl1 curl && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . /app

# Upgrade pip and install minimal dependencies
RUN pip install --no-cache-dir --upgrade pip setuptools wheel
RUN pip install "Pillow<10" fastapi uvicorn streamlit easyocr

# Expose ports
EXPOSE 8000
EXPOSE 8501

# Entrypoint
ENTRYPOINT ["/usr/bin/tini", "--"]

# Run FastAPI and Streamlit together
CMD ["bash", "-c", "uvicorn Api.Deploy_fastapi:app --host 0.0.0.0 --port 8000 & streamlit run main.py --server.port=8501 --server.address=0.0.0.0"]
